### ISSUE TITLE
You cannot log in with "Facebook" on Instagram, if it is assigned to a different container

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/contain-facebook#103]
**[Affected versions]:**
- Firefox 59.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the Firefox Multi-Account Containers add-on (6.0.0) installed.
- Have the "https://www.instagram.com/" assigned to a container.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Go to the "about:addons" page and install the "Facebook Container" add-on (1.3.0).
3. Navigate to the https://www.instagram.com/ website and click the "Log in with Facebook" button.
4. Enter you credentials and press the "Log In" button.
5. Observe the behavior.

**[Expected result]:**
- You are successfully logged in to "Instagram".

**[Actual result]:**
- Instagram is opened in a new container tab and you are not logged in.

**[Notes]:**
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/38307700-42414e58-381d-11e8-9d19-c08bc0b0e2a9.gif)

**Comment by ryanfeeley** [comment]
I’m struggling to imagine way for us to support manual containers (MAC) and automatic containers (Facebook Container). I'm not saying it's impossible, but that it’s not a quick fix.

For now, I propose this is an either/or solution. You manage your containers manually (very advanced users) or you simply want to contain a limited number of domains (mainstream appeal).

Much like driving a car, you have to choose which one works best. A hybrid solution requires a lot more of the user.

**Comment by TanviHacks** [comment]
For this, I think we need to go back to a UI alert on install that Ryan has proposed before.  Let’s do that in a 1.3.1 release.! In the meantime, let’s update AMO pages to highlight this.

From a coding standpoint if we want to do something in 1.3.0, we could either:
1)  find Instagram container and delete it.  This one is not great for usability, because there could be data loss that requires a relogin
2)  find Instagram container, rename it to Facebook.  This one is not great in the privacy perspective,  because there may be a number of non-Facebook credentials in this container already.

**Comment by stoically** [comment]
This should be solved with the upcoming release since the domains `instagram.com` and `www.instagram.com` are now included.

**Comment by stoically** [comment]
Snap, I didn't pay attention. This is about MAC assignment, please disregard my last comment - @TanviHacks is of course right.

**Comment by stoically** [comment]
Let me try to add something useful instead of just noise: A possible way to unbreak (most of the) "Login with Facebook" buttons (that rely on cookies) in combination with the Facebook Container could be:

* Have Multi-Account Containers check if Facebook Container is installed
* If it is installed ignore all requests that go to OAuth relevant Facebook Endpoints, such as:
  * `https://www.facebook.com/dialog/oauth*`
  * `https://www.facebook.com/login.php?*&next=https://www.facebook.com/v1.0/dialog/oauth*`

**Comment by TanviHacks** [comment]
I will add messages to AMO pages about how you should unassign Instagram etc before using Facebook Container.

**Comment by stoically** [comment]
Opened PR #107 as proposal for possible solution, might need some refinement and might not at all what's wanted here. Only tested with this specific site and use-case.

**Comment by TanviHacks** [comment]
This should be solved with #113 and mozilla/multi-account-containers#1182 instead.

**Comment by TanviHacks** [comment]
@SoftVision-PaulOiegas has this been retested with 1.4.0?

**Comment by SoftVision-PaulOiegas** [comment]
@TanviHacks Not sure, but I've re-verified it now and it still reproduces on latest 1.4.0 build from #130.

**Comment by TanviHacks** [comment]
@bakulf can you test with the STR.  And then also test with a restart before navigating to instagram?

**Comment by BuddhiAbeyratne** [comment]
this still breaks oath on other websites that provide Facebook login to users

**Comment by AAbouZaid** [comment]
The same issue happens with meetup.com
