### ISSUE TITLE
The "View Image" context menu option no longer works for web.whatsapp.com

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/contain-facebook#131]
**[Affected versions]:**
- Firefox 59.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Latest Firefox Container build (v.1.3.1) cloned from the repository master was installed on a new profile.
- You are already logged on web.whatsapp.com and have a conversation with a shared image. 

**[Steps to reproduce]:*
1. Open the browser with the profile from prerequisites.
2. Navigate to web.whatsapp.com website.
3. Open a conversation with an image shared and right-click the image.
4. Left click or middle click on the "View Image" option from context menu.
5. Observe the behavior.

[Expected result]:
- The image is opened in the same/new tab outside of whatsapp website.

[Actual result]:
- The image is not opened in the same tab with left click and when scroll click is used, a blank page is displayed in a new tab.

[Notes]:
- This issue does not occur when Facebook Container is not installed (see attached video).
- Here is a screen recording of the issue: https://goo.gl/uYMKqz

**Comment by jonathanKingston** [comment]
This was bundled into:https://github.com/mozilla/contain-facebook/pull/130 I think this is resolved.

**Comment by SoftVision-PaulOiegas** [comment]
@jonathanKingston Nope, still reproducing on the latest build provided on #130.

**Comment by TanviHacks** [comment]
@jonathanKingston can you test this locally and see what you get?

**Comment by bakulf** [comment]
I'm not able to reproduce this issue. The opening of the image happens correctly in the same tab, or in a new tab if I press 'shift' key when clicking on 'view image' item from the context menu.
What is broken is the opening in a new window: pressing 'CTRL' key I should see the image opened in a new window, but this doesn't happen. A new window is shown, but the image is not loaded.

**Comment by bakulf** [comment]
This is a bug in firefox, completely unrelated to this extension. Bug 1459562.

**Comment by SoftVision-PaulOiegas** [comment]
@bakulf have you tested this scenario with the 1.4.0 try build from #130 or with the [AMO version](https://addons.mozilla.org/en-US/firefox/addon/facebook-container/?src=search)? I'm asking because with the AMO version this might seem to be working because `whatsapp` domains are not yet added in that version. This only breaks on 1.4.0 where the `whatsapp` domains were added.

**Comment by TanviHacks** [comment]
@SoftVision-PaulOiegas can you test this in 1.4.0 with Firefox 62?

@bakulf can you retest in release and in Firefox 62?

**Comment by SoftVision-PaulOiegas** [comment]
Hey @TanviHacks, sure. I've tested the 1.4.0 build together with MAC 7.0.0 build and found out the next behaviors:
- Firefox 60.0.1 (current Release version) - Issue is not reproducing
- Firefox 61.0b6 (current Beta version) - Issue is reproducing
- Firefox 62.0a1 (2018-05-23 current Nightly version) - Issue is reproducing

Considering this, I've used the mozregression tool to check for a regression window. It seems that the last good build was in 2018-04-09 and first bad build on 2018-04-10.

Last good revision: 70ab5d0f6da37783913e39857edf488ccfc2ab7b
First bad revision: de33fb39fa4878714120d06ce6a0c72179016be9
Pushlog: https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=70ab5d0f6da37783913e39857edf488ccfc2ab7b&tochange=de33fb39fa4878714120d06ce6a0c72179016be9

From what I see in the pushlog, the issue that affects this functionality in newer versions of Firefox, might be the issue that @jonathanKingston worked on [#1252998](https://bugzilla.mozilla.org/show_bug.cgi?id=1252998).

This clearly needs to be fixed either on our end or on Firefox, otherwise starting with next Fx61 release, all users will start to be affected by this issue.

**Comment by TanviHacks** [comment]
@jonathanKingston Do you know why your patches in https://bugzilla.mozilla.org/show_bug.cgi?id=1252998 woudl cause this bug?

**Comment by TanviHacks** [comment]
Actually, it looks like @bakulf landed that patch.  baku, can you take a look?

**Comment by maxxcrawford** [comment]
Is this still reproducible on the latest version of the add-on (2.1.1) and Firefox (77.0.1)?
